/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b8f8ee04d1981dbf781f3d5a48c84838)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  JOURNEYS: DurableObjectNamespace<import("./src/server/worker").JourneyCoordinator>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server/worker");
    durableNamespaces: "JourneyCoordinator";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
